version: '3.8'

services:
    app:
        build:
            context: /home/lanth/docker-test
            dockerfile: Dockerfile
        container_name: laravel_app
        volumes:
            - /home/lanth/docker-test:/var/www
        networks:
            - app-network

    nginx:
        image: nginx:alpine
        container_name: nginx_server
        ports:
            - "8080:80"
        volumes:
            - /home/lanth/docker-test:/var/www
            - /home/lanth/docker-test/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - app-network

    db:
        image: mysql:8
        container_name: laravel_db
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    db_data:
